### ISSUE TITLE
Add @IRI annotations to interface types

### ISSUE THREAD

**Issue by kenwenzel** [admin-shell-io/java-model#2]
I wonder if it is possible to add the `@IRI` annotations also to interface declarations and not only to getters.
Maybe this would allow to use a framework like KOMMA for RDF object mapping.
An example using KOMMA's `@iri` annotation can be found at:
https://github.com/komma/komma/blob/master/bundles/vocab/net.enilink.vocab.owl/src/main/java/net/enilink/vocab/owl/Class.java

Best regards,
Ken

**Comment by sebbader** [comment]
@kenwenzel not sure if this issue has been solved in the meantime, e.g. at https://github.com/eclipse-digitaltwin/aas4j/blob/main/model/src/main/java/io/adminshell/aas/v3/model/impl/DefaultAssetAdministrationShell.java 
If not, please reopen the ticket in the new repository at https://github.com/eclipse-digitaltwin/aas4j/issues
